### ISSUE TITLE
Contains friendly navigation and responsive design

### ISSUE THREAD

**Issue by David5p** [David5p/The-Ashes-2025-2026#1]
**User story:**

When using the website for the first time, I need a simple navigation system with user friendly design. It needs to work well on mobile, tablet and desktop without issues.

**Acceptance Criteria**

- [x] The website is fully responsive across all devices and screen sizes.
- [x] Site layout and navigation are functional and allow easy access to different sections of the website.

**Tasks**

- [x] Use responsive design principles from Bootstrap to ensure the website is works well on various devices.
- [ ] 
- [x] Arrange the site layout and navigation based on best practices, ensuring all key sections and pages are easily accessible.
