### ISSUE TITLE
Up to date information

### ISSUE THREAD

**Issue by David5p** [David5p/The-Ashes-2025-2026#2]
**User story:**  

As a cricket fan, I want to come to the site and have access to the latest information and discussion points ahead of the Ashes so I can trust the website is the place to go to for my Ashes news.

**Acceptance Criteria**

- [x] The website has the latest news on it.

**Tasks**

- [x] The homepage features a paragraph previewing the upcoming Ashes.
- [x] There is a ‘Players to Watch’ section featuring information and photos.
- [x] There is a ‘sign up to the newsletter’ button where visitors can receive the latest news.
