### ISSUE TITLE
High quality images

### ISSUE THREAD

**Issue by David5p** [David5p/The-Ashes-2025-2026#3]
**User Story: High quality images**

As a visitor, I want to see enticing and exciting images of the players expected to feature in The Ashes.

**Acceptance Criteria**

- [x] The website features high quality images users can look through.
- [x] They are produced in a layout which works well on all devices.

**Tasks**

- [x] Integrate provided high-quality images of current players for use in the gallery section in a layout which works well on all devices using the bootstrap grid system.
- [ ] 
- [x] Choose an eye-catching hero image.
