### ISSUE TITLE
Contact information

### ISSUE THREAD

**Issue by David5p** [David5p/The-Ashes-2025-2026#4]
**User Story:**

As a cricket fan,  I need to be able to engage with the latest news so I can talk to others about it.

**Acceptance Criteria**

- [x] The website contains a dedicated section for contact details.
- [x] The contact section includes social media.
- [x] This section is visible and accessible from all parts of the website.

**Tasks**

- [x] Design a section contact details, and social media links with icons.
- [x] The section will be visible on all website pages in the navigation bar.
