### ISSUE TITLE
Schedule of The Ashes

### ISSUE THREAD

**Issue by David5p** [David5p/The-Ashes-2025-2026#5]
User Story 5:

**Schedule of The Ashes** 

- [x] User Story: As a cricket fan,  I need to know when the Ashes are taking place including the dates of each Test and the location so I can follow the event.

**Acceptance Criteria**

- [x] The website contains a dedicated page for the schedule.
- [x] The schedule contains clear and concise information about the upcoming Ashes. 
- [x] The page is visible on the navigation bar on all parts of the website.

**Tasks**

- [x] Design a page which includes all the details of the five tests.
- [x] Feature all the information known about The England Lions tour which precedes The Ashes.
- [x] Ensure the page is functional on all devices.
