### ISSUE TITLE
Booking form

### ISSUE THREAD

**Issue by David5p** [David5p/The-Ashes-2025-2026#6]
**User Story:** 

As a cricket fan,  I want to be able to engage in the news I am receiving and ask and receive answers to questions in a podcast.

**Acceptance Criteria**

- [ ] The website contains a feature where users can register for access to a podcast.
- [ ] The feature is visible on the navigation bar on all parts of the website.
- [ ] Feedback to the user their submission is successful.

**Tasks**

- [ ] Create a button and accompanying form where users can sign up to the monthly podcast for the latest Ashes news.
- [ ] 
- [ ] The form must contain a question section providing visitors the opportunity to interact with the site.
- [ ] 
- [ ] Feedback to the user their submission is successful with a dedicated submission page.
- [ ] 
- [ ] The form must be fully functional and users need to complete all sections before submission is allowed.

**Comment by David5p** [comment]
I did not have time to complete this feature of the website.
