### ISSUE TITLE
Pick your team for The Ashes

### ISSUE THREAD

**Issue by David5p** [David5p/The-Ashes-2025-2026#7]
**User Story:**

 As a cricket fan,  I want to be able to engage in the news I am receiving and pick my team so I can se how the teams will line up against one another.

**Acceptance Criteria**

- [ ] The website contains a feature where users can pick their Ashes 11 for each side.
- [ ] The feature is visible on the navigation bar on all parts of the website.

**Tasks**

- [ ] Create a dropdown menu of players for each side eligible for selection.
- [ ] 
- [ ] Ensure users must select 11 players for each side before submission is allowed.
- [ ] 
- [ ] The form must be fully functional and users need to fill in all players  before submission is allowed.
- [ ] 
- [ ] Feedback to the user their submission is successful with a dedicated submission page.

**Comment by David5p** [comment]
I did not have time to complete this feature of the website.
