### ISSUE TITLE
Wildcards page

### ISSUE THREAD

**Issue by David5p** [David5p/The-Ashes-2025-2026#8]
**User Story:** 

As a cricket fan,  I want to know which players I should look out for ahead of The Ashes and may make a late surge to be in the team. 

**Acceptance Criteria**

- [ ] The website contains a dedicated page for the wild card section
- [ ] The page contains clear information about who the players are and why they are under consideration to be selected. 
- [ ] The page is visible on the navigation bar on all parts of the website.

**Tasks**

- [ ] Design a page which includes details on at least 3 players from each side who could feature in the upcoming Ashes.
- [ ] 
- [ ] Ensure page has the same design format for profiling each player.

**Comment by David5p** [comment]
I did not have time to complete this feature of the website.

**Comment by David5p** [comment]
I did not have time to complete this feature of the website.
